# Generated by Django 6.0.4 on 2026-04-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nominal_default', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('wajib_per_semester', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('aktif', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semester',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('kelas', models.CharField(max_length=30)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField()),
                ('periode', models.CharField(blank=True, max_length=20, null=True)),
                ('jatuh_tempo', models.DateField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_set', to='bendahara.jenispembayaran')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_set', to='bendahara.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_set', to='bendahara.siswa')),
            ],
            options={
                'verbose_name': 'Tagihan',
                'verbose_name_plural': 'Tagihan',
                'ordering': ['-id'],
                'unique_together': {('siswa', 'jenis', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_bayar', models.IntegerField()),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('metode', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran_set', to='bendahara.tagihan')),
            ],
        ),
    ]
