# Generated by Django 6.0.4 on 2026-04-21 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendahara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.CharField(blank=True, max_length=32, unique=True)),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('metode', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_pembayaran_set', to='bendahara.semester')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_pembayaran_set', to='bendahara.siswa')),
            ],
            options={
                'verbose_name': 'Transaksi Pembayaran',
                'verbose_name_plural': 'Transaksi Pembayaran',
                'ordering': ['-tanggal_bayar', '-id'],
            },
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='transaksi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran_set', to='bendahara.transaksipembayaran'),
        ),
    ]
