# Generated by Django 6.0.4 on 2026-04-21 08:42

from django.db import migrations, models


def mark_existing_spp_as_monthly(apps, schema_editor):
    JenisPembayaran = apps.get_model('bendahara', 'JenisPembayaran')
    JenisPembayaran.objects.filter(nama__icontains='spp').update(
        is_bulanan=True,
        jumlah_bulan_per_semester=6,
    )


def unmark_existing_spp_as_monthly(apps, schema_editor):
    JenisPembayaran = apps.get_model('bendahara', 'JenisPembayaran')
    JenisPembayaran.objects.filter(nama__icontains='spp').update(
        is_bulanan=False,
        jumlah_bulan_per_semester=6,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bendahara', '0002_transaksipembayaran_pembayaran_transaksi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagihan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jenispembayaran',
            name='is_bulanan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jenispembayaran',
            name='jumlah_bulan_per_semester',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='tagihan',
            name='urutan_periode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='periode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tagihan',
            constraint=models.UniqueConstraint(fields=('siswa', 'jenis', 'semester', 'urutan_periode'), name='unique_tagihan_periode_siswa'),
        ),
        migrations.RunPython(mark_existing_spp_as_monthly, unmark_existing_spp_as_monthly),
    ]
