# Generated by Django 6.0.4 on 2026-04-21 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendahara', '0003_alter_tagihan_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pengeluaran', models.CharField(blank=True, max_length=32, unique=True)),
                ('judul', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('tanggal_pengeluaran', models.DateField(default=django.utils.timezone.localdate)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_keluar_set', to='bendahara.semester')),
            ],
            options={
                'verbose_name': 'Kas Keluar',
                'verbose_name_plural': 'Kas Keluar',
                'ordering': ['-tanggal_pengeluaran', '-id'],
            },
        ),
    ]
