# Generated by Django 6.0.4 on 2026-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bendahara', '0004_kaskeluar'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='pondok',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
